### ISSUE TITLE
error raised when attempting to get float and uncertainty exceeds number by order of magnitued

### ISSUE THREAD

**Issue by MikeBusuttil** [drakegroup/sigfig#22]
```py
>>> round(2.6907081179483057, 1.647845041384315, type=float)
3.0
```
however
```py
>>> round(2.6907081179483057, 11.647845041384315, type=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mike/kaggle/.venv/lib/python3.11/site-packages/sigfig/sigfig.py", line 621, in round
    return num.output(given['output_type'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/kaggle/.venv/lib/python3.11/site-packages/sigfig/sigfig.py", line 183, in output
    return output_type(Decimal(self.decimate(no_formatting, zeropadding=False) +\
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by MikeBusuttil** [comment]
✅fixed
